plugins {
    id 'org.moddingx.modgradle.meta' version '5.1.5'
}

repositories {
    maven {
        url = "https://maven.blamejared.com"
    }
    maven {
        url = "https://modmaven.dev/"
    }
    maven {
        name = "ModdingX"
        url = 'https://maven.moddingx.org/'
    }
    maven {
        name = "Curios"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name = "MelanX"
        url = "https://maven.melanx.de/release"
    }
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var baseVersion = '26.1'
var libxVersion = '26.1.2-7.0.2'
var jeiVersion = '29.21.0.66'
var curiosVersion = '15.0.0+26.1.2'
var jadeVersion = '8326300' // 26.1.8
var quarkVersion = '4.1-472-SNAPSHOT'
var zetaVersion = '1.1-37-SNAPSHOT'

mod.configure {
    modid 'utilitix'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base baseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge project.hasProperty('neo_version') ? project.neo_version : "${baseVersion}.2.99"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/UtilitiX'

    artifacts {
        useJarJar()
        sources {
            publishToRepositories()
        }
    }

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name = 'melanx'
            url = 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type 'beta'
            require 'libx'
            optional 'jade'
            optional 'jei'
            version '26.1.2'
            environmentType 'client_and_server'
        }
        curseforge {
            projectId 463703
        }
        modrinth {
            projectId 'MMMWYsjm'
        }
    }

    runs {
        all {
            dependencies {
                runtime project(":coremods")
            }
        }
    }
}

dependencies {
    annotationProcessor "org.moddingx:LibX:${libxVersion}"

    implementation "org.moddingx:LibX:${libxVersion}"
    implementation "mezz.jei:jei-${baseVersion}.2-neoforge:${jeiVersion}"
    implementation "top.theillusivec4.curios:curios-neoforge:${curiosVersion}"
    implementation "curse.maven:jade-324717:${jadeVersion}"

    runtimeOnly "de.melanx:RecipePrinter:26.1.1"

    compileOnly "org.violetmoon.quark:Quark:${quarkVersion}"
    compileOnly "org.violetmoon.zeta:Zeta:${zetaVersion}"
    compileOnly(jarJar(project(":coremods")))
}
