plugins {
    id 'org.moddingx.modgradle.meta' version '5.0.4'
}

repositories {
    maven {
        url = "https://modmaven.dev/"
    }
    maven {
        name = "ModdingX"
        url = 'https://maven.moddingx.org/'
    }
    maven {
        name = "Curios"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var baseVersion = '21.1'
var libxVersion = '1.21.1-6.0.8'
var jeiVersion = '19.25.0.324'
var curiosVersion = '9.5.1+1.21.1'
var jadeVersion = '6853386' // 1.21.1-NeoForge-15.10.3
var quarkVersion = '4.1-469-SNAPSHOT'
var zetaVersion = '1.1-35-SNAPSHOT'

mod.configure {
    modid 'utilitix'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base baseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge project.hasProperty('neo_version') ? project.neo_version : "${baseVersion}.213"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/UtilitiX'

    artifacts {
        sources {
            publishToRepositories()
        }
    }

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type 'beta'
            require 'libx'
            optional 'jade'
            optional 'jei'
        }
        curseforge {
            projectId 463703
        }
        modrinth {
            projectId 'MMMWYsjm'
        }
    }
}

dependencies {
    annotationProcessor "org.moddingx:LibX:${libxVersion}"

    implementation "org.moddingx:LibX:${libxVersion}"
    implementation "mezz.jei:jei-1.${baseVersion}-neoforge:${jeiVersion}"
    implementation "top.theillusivec4.curios:curios-neoforge:${curiosVersion}"
    implementation "curse.maven:jade-324717:${jadeVersion}"

    compileOnly "org.violetmoon.quark:Quark:${quarkVersion}"
    compileOnly "org.violetmoon.zeta:Zeta:${zetaVersion}"
}
