modLoader = "javafml"
loaderVersion="[${fml},)"
license = "Apache License 2.0"
issueTrackerURL = "https://www.github.com/MelanX/UtilitiX/issues/"

[[mods]]
modId = "utilitix"
version="${version}"
displayName = "UtilitiX"
updateJSONURL = "https://assets.melanx.de/updates/utilitix.json"
displayURL = "www.curseforge.com/members/melanx/"
credits = "Thanks to noeppi_noeppi who put a lot of work in this mod, too"
authors = "MelanX, noeppi_noeppi"
description = '''
A lot of items, nice to have
'''

[[dependencies.utilitix]]
    modId = "forge"
    mandatory = true
    versionRange="[${forge},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "minecraft"
    mandatory = true
    versionRange="[${minecraft},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "libx"
    mandatory = true
    versionRange="[1.20.1-5.0.1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "jade"
    mandatory = false
    versionRange = "[11.4.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "jei"
    mandatory = false
    versionRange = "[15.0.0.12,)"
    ordering = "BEFORE"
    side = "BOTH"
