modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache License 2.0"
issueTrackerURL = "https://www.github.com/MelanX/UtilitiX/issues/"

[[mods]]
modId = "utilitix"
version = "${file.jarVersion}"
displayName = "UtilitiX"
updateJSONURL = "https://assets.melanx.de/updates/utilitix.json"
displayURL = "www.curseforge.com/members/melanx/"
credits = "Thanks to noeppi_noeppi who put a lot of work in this mod, too"
authors = "MelanX, noeppi_noeppi"
description = '''
A lot of items, nice to have
'''

[[dependencies.utilitix]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.0.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2, 1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "libx"
    mandatory = true
    versionRange = "[1.18.2-3.2.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "jade"
    mandatory = false
    versionRange = "[1.18.2-3.2.0,)"
    ordering = "NONE"
    side = "BOTH"
