modLoader = "javafml"
loaderVersion = "[37,)"
license = "Apache License 2.0"
issueTrackerURL = "https://www.github.com/MelanX/UtilitiX/issues/"

[[mods]]
modId = "utilitix"
version = "${file.jarVersion}"
displayName = "UtilitiX"
updateJSONURL = "https://assets.melanx.de/updates/utilitix.json"
displayURL = "www.curseforge.com/members/melanx/"
#logoFile="utilitix.png"
credits = ""
authors = "MelanX, noeppi_noeppi"
description = '''
A lot of items, nice to have
'''

[[dependencies.utilitix]]
    modId = "forge"
    mandatory = true
    versionRange = "[37.0.95,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1, 1.18)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "libx"
    mandatory = true
    versionRange = "[1.17.1-2.1.12,)"
    ordering = "NONE"
    side = "BOTH"