modLoader = "javafml"
loaderVersion = "[34,)"
license = "Apache License"
issueTrackerURL = "http://www.github.com/MelanX/UtilitiX/issues/"

[[mods]]
modId = "utilitix"
version = "${file.jarVersion}"
displayName = "Mod ID"
updateJSONURL = "https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/utilitix.json"
displayURL = "www.curseforge.com/members/melanx/"
#logoFile="utilitix.png"
credits = ""
authors = "MelanX"
description = '''

'''

[[dependencies.utilitix]]
    modId = "forge"
    mandatory = true
    versionRange = "[34,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3, 1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.utilitix]]
    modId = "libx"
    mandatory = true
    versionRange = "[1.16.3-1.0.27,)"
    ordering = "NONE"
    side = "BOTH"