modLoader = "javafml"
loaderVersion = "[34,)"
license = "Apache License"
issueTrackerURL = "http://www.github.com/MelanX/modid/issues/"

[[mods]]
modId = "modid"
version = "${file.jarVersion}"
displayName = "Mod ID"
updateJSONURL = "https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/modid.json"
displayURL = "www.curseforge.com/members/melanx/"
#logoFile="modid.png"
credits = ""
authors = "MelanX"
description = '''

'''

[[dependencies.modid]]
    modId = "forge"
    mandatory = true
    versionRange = "[34,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.modid]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3, 1.17)"
    ordering = "NONE"
    side = "BOTH"
